name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Her gün çalıştırır

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push GitHub Snake Contribution Grid
        run: |
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Generate snake contribution grid"
          git push
